package models

import (
	"time"

	"gorm.io/gorm"
)

// User represents a trader using the Copilot
type User struct {
	gorm.Model
	Email        string `gorm:"uniqueIndex;not null" json:"email"`
	PasswordHash string `gorm:"not null" json:"-"`
	Name         string `json:"name"`
	Role         string `gorm:"default:'user'" json:"role"` // 'user' or 'admin'
	SubscriptionTier string `gorm:"default:'free'" json:"subscription_tier"`
	
	// Integrations
	TelegramID   string `gorm:"index;default:null" json:"telegram_id"`
	AngelClient  string `json:"angel_client"`
	AngelPin     string `json:"angel_pin"`
	AngelAPIKey  string `json:"angel_api_key"`
	ClaudeAPIKey string `json:"claude_api_key"`
	BinanceAPIKey string `json:"binance_api_key"`
	BinanceSecret string `json:"binance_secret"`

	// 2FA / Security
	TOTPSecret   string `json:"-"`
	TOTPEnabled  bool   `gorm:"default:false" json:"totp_enabled"`
}

// TradeLog records AI generated trade executions
type TradeLog struct {
	gorm.Model
	UserID        uint
	TradingSymbol string
	OrderType     string
	Quantity      int
	Price         float64
	Status        string
	OrderID       string // Added to track AngelOne order status
	ExecutedAt    time.Time
}

// AIInsight records trade proposals generated by the Python AI Engine (legacy/simple)
type AIInsight struct {
	gorm.Model
	Symbol          string  `json:"symbol"`
	Exchange        string  `gorm:"default:'NSE'" json:"exchange"`
	Ltp             float64 `json:"ltp"`
	Target          float64 `json:"target"`
	StopLoss        float64 `json:"stop_loss"`
	Action          string  `json:"action"` // LONG or SHORT
	Risk            string  `json:"risk"`   // Safe or Risky
	Reasoning       string  `json:"reasoning"`
	ConvictionScore string  `json:"conviction_score"`
	RawText         string  `json:"raw_text"` // Original LLM text (deprecated)
}

// Signal represents an AI-generated trading signal with full audit trail
type Signal struct {
	gorm.Model
	Symbol          string  `json:"symbol"`
	Exchange        string  `gorm:"default:'NSE'" json:"exchange"` // NSE or BINANCE
	Action          string  `json:"action"` // LONG or SHORT
	EntryPrice      float64 `json:"entry_price"`
	Target          float64 `json:"target"`
	StopLoss        float64 `json:"stop_loss"`
	ConvictionScore string  `json:"conviction_score"`
	Reasoning       string  `json:"reasoning"`
	NewsContext     string  `json:"news_context"`
	Stage1Raw       string  `json:"stage1_raw"`
	Stage2Filtered  string  `json:"stage2_filtered"`
	Stage3Final     string  `json:"stage3_final"`
	Status          string  `gorm:"default:'ACTIVE'" json:"status"` // ACTIVE, CLOSED
}

// PaperTrade represents a simulated trade execution
type PaperTrade struct {
	gorm.Model
	SignalID    uint      `json:"signal_id"`
	UserID      uint      `json:"user_id"`
	Symbol      string    `json:"symbol"`
	Exchange    string    `gorm:"default:'NSE'" json:"exchange"` // NSE or BINANCE
	Action      string    `json:"action"` // LONG or SHORT
	EntryPrice  float64   `json:"entry_price"`
	Quantity    int       `json:"quantity"`
	EntryTime   time.Time `json:"entry_time"`
	ExitPrice   float64   `json:"exit_price"`
	ExitTime    time.Time `json:"exit_time"`
	ExitReason  string    `json:"exit_reason"` // TARGET, STOP_LOSS, MANUAL
	PnLAmount   float64   `json:"pnl_amount"`
	PnLPercent  float64   `json:"pnl_percent"`
	Status      string    `gorm:"default:'OPEN'" json:"status"` // OPEN, CLOSED
}

// PortfolioSnapshot records daily portfolio state per user
type PortfolioSnapshot struct {
	gorm.Model
	UserID        uint      `json:"user_id"`
	Date          time.Time `json:"date"`
	TotalValue    float64   `json:"total_value"`
	CashBalance   float64   `json:"cash_balance"`
	InvestedValue float64   `json:"invested_value"`
	DayPnL        float64   `json:"day_pnl"`
	TotalPnL      float64   `json:"total_pnl"`
}

// Subscription tracks user's payment and access tier
type Subscription struct {
	gorm.Model
	UserID     uint      `json:"user_id"`
	Tier       string    `json:"tier"` // free, pro, elite
	StartedAt  time.Time `json:"started_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	RazorpayID string    `json:"razorpay_id"`
	Status     string    `gorm:"default:'ACTIVE'" json:"status"` // ACTIVE, CANCELLED, EXPIRED
}
